-- Реквизиты организации
ALTER TABLE club_settings
  ADD COLUMN IF NOT EXISTS org_full_name TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS org_inn TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS org_kpp TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS org_ogrn TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS org_legal_address TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS org_bank_name TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS org_bik TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS org_account TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS org_corr_account TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS org_director TEXT DEFAULT NULL;

-- Таблица платёжных документов
CREATE TABLE IF NOT EXISTS org_documents (
  id SERIAL PRIMARY KEY,
  doc_type VARCHAR(50) NOT NULL,
  doc_number VARCHAR(100),
  doc_date DATE NOT NULL DEFAULT CURRENT_DATE,
  amount NUMERIC(12,2) DEFAULT 0,
  description TEXT,
  status VARCHAR(50) DEFAULT 'issued',
  booking_id INTEGER DEFAULT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);
